@echo off
echo [TeemChat] Syncing .env to .env.json...
dart run scripts/sync_env.dart
echo [TeemChat] Starting local development server on Chrome...
flutter run -d chrome --dart-define-from-file=.env.json
