import os

# Write the new tile_map.dart with true pixel-art rendering
# Key technique: render internally at HALF size coordinates, then canvas.scale(2,2)
# This makes every drawn pixel appear as a 2x2 block — authentic GBA look

lines = []
def L(s): lines.append(s)

L("import 'package:flame/components.dart';")
L("import 'package:flutter/material.dart';")
L("import '../../../../core/constants/app_colors.dart';")
L("import 'furniture_item.dart';")
L("import 'obstacle_wall.dart';")
L("")
L("// ============================================================")
L("// TRUE PIXEL-ART WORLD MAP — GBA Pokémon FireRed / Emerald style")
L("// Internal render resolution = mapWidth/2 x mapHeight/2")
L("// canvas.scale(2, 2) makes every pixel a visible 2×2 block.")
L("// All coordinates are in INTERNAL pixels (half of world coords).")
L("// Grid unit T = 8 internal px = 16 world px.")
L("// NO anti-aliasing, NO gradients, NO curves. Rects only.")
L("// ============================================================")
L("class WorldMapComponent extends Component {")
L("  static const double mapWidth  = 1680;")
L("  static const double mapHeight = 1080;")
L("  static const double wallThick = 32.0;")
L("")
L("  // World-space grid unit")
L("  static const double G = 16.0;")
L("")
L("  // Internal (half-resolution) tile size. Each tile = 8x8 internal px = 16x16 screen px.")
L("  static const int T = 8;")
L("  // Internal canvas dimensions")
L("  static const int IW = 840; // mapWidth / 2")
L("  static const int IH = 540; // mapHeight / 2")
L("")
L("  // Paint with pixel-perfect settings (no AA)")
L("  static Paint _px(Color c) => Paint()")
L("    ..color = c")
L("    ..isAntiAlias = false")
L("    ..filterQuality = FilterQuality.none;")
L("")
L("  // Draw a rect in INTERNAL coordinates (will be 2x on screen)")
L("  static void _r(Canvas c, int x, int y, int w, int h, Color col) {")
L("    c.drawRect(Rect.fromLTWH(x.toDouble(), y.toDouble(), w.toDouble(), h.toDouble()), _px(col));")
L("  }")
L("")
L("  @override")
L("  Future<void> onLoad() async {")
L("    await super.onLoad();")
L("    _addBoundaryWalls();")
L("    _addBuildingHitboxes();")
L("    _addWaterBarriers();")
L("    _addWorldProps();")
L("  }")
L("")
L("  void _addBoundaryWalls() {")
L("    add(ObstacleWall(position: Vector2(0, 0), size: Vector2(mapWidth, wallThick), isVisible: false));")
L("    add(ObstacleWall(position: Vector2(0, mapHeight - wallThick), size: Vector2(mapWidth, wallThick), isVisible: false));")
L("    add(ObstacleWall(position: Vector2(0, 0), size: Vector2(wallThick, mapHeight), isVisible: false));")
L("    add(ObstacleWall(position: Vector2(mapWidth - wallThick, 0), size: Vector2(wallThick, mapHeight), isVisible: false));")
L("  }")
L("")
L("  void _addBuildingHitboxes() {")
L("    add(ObstacleWall(position: Vector2(G*5, G*5), size: Vector2(G*12, G*8), isVisible: false));")
L("    add(ObstacleWall(position: Vector2(G*20, G*4), size: Vector2(G*14, G*9), isVisible: false));")
L("  }")
L("")
L("  void _addWaterBarriers() {")
L("    add(ObstacleWall(position: Vector2(G*85, G*2), size: Vector2(G*2, mapHeight), isVisible: false));")
L("    add(ObstacleWall(position: Vector2(G*46, G*26), size: Vector2(G*4, mapHeight - G*26), isVisible: false));")
L("  }")
L("")
L("  void _addWorldProps() {")
L("    add(FurnitureComponent(type: FurnitureType.stoneWell,     position: Vector2(G*18, G*14)));")
L("    add(FurnitureComponent(type: FurnitureType.woodenSign,    position: Vector2(G*14, G*14)));")
L("    add(FurnitureComponent(type: FurnitureType.streetLantern, position: Vector2(G*5, G*14)));")
L("    add(FurnitureComponent(type: FurnitureType.streetLantern, position: Vector2(G*34, G*14)));")
L("    add(FurnitureComponent(type: FurnitureType.streetLantern, position: Vector2(G*18, G*27)));")
L("    add(FurnitureComponent(type: FurnitureType.woodenFence,   position: Vector2(G*5, G*22)));")
L("    add(FurnitureComponent(type: FurnitureType.woodenFence,   position: Vector2(G*8, G*22)));")
L("    add(FurnitureComponent(type: FurnitureType.flowerPatch,   position: Vector2(G*5, G*24)));")
L("    add(FurnitureComponent(type: FurnitureType.flowerPatch,   position: Vector2(G*8, G*24)));")
L("    add(FurnitureComponent(type: FurnitureType.flowerPatch,   position: Vector2(G*18, G*12)));")
L("    add(FurnitureComponent(type: FurnitureType.logBench,      position: Vector2(G*23, G*24)));")
L("    add(FurnitureComponent(type: FurnitureType.berryBush,     position: Vector2(G*32, G*21)));")
L("    add(FurnitureComponent(type: FurnitureType.berryBush,     position: Vector2(G*32, G*25)));")
L("    add(FurnitureComponent(type: FurnitureType.pineTree,      position: Vector2(G*36, G*8)));")
L("    for (final v in [")
L("      Vector2(G*43,G*6),Vector2(G*46,G*6),Vector2(G*49,G*6),")
L("      Vector2(G*43,G*9),Vector2(G*46,G*9),Vector2(G*49,G*9),")
L("      Vector2(G*62,G*10),Vector2(G*65,G*10),Vector2(G*68,G*10),")
L("      Vector2(G*62,G*13),Vector2(G*65,G*13),Vector2(G*68,G*13),")
L("    ]) { add(FurnitureComponent(type: FurnitureType.tallGrass, position: v)); }")
L("    for (final v in [")
L("      Vector2(G*39,G*3),Vector2(G*53,G*3),Vector2(G*58,G*3),Vector2(G*72,G*4),Vector2(G*76,G*8),")
L("      Vector2(G*39,G*18),Vector2(G*48,G*20),Vector2(G*59,G*19),Vector2(G*70,G*18),Vector2(G*74,G*23),")
L("    ]) { add(FurnitureComponent(type: FurnitureType.pineTree, position: v)); }")
L("    add(FurnitureComponent(type: FurnitureType.berryBush,  position: Vector2(G*54, G*10)));")
L("    add(FurnitureComponent(type: FurnitureType.flowerPatch,position: Vector2(G*42, G*14)));")
L("    add(FurnitureComponent(type: FurnitureType.woodenSign, position: Vector2(G*43, G*19)));")
L("    add(FurnitureComponent(type: FurnitureType.campfire,   position: Vector2(G*58, G*35)));")
L("    add(FurnitureComponent(type: FurnitureType.tent,       position: Vector2(G*52, G*33)));")
L("    add(FurnitureComponent(type: FurnitureType.tent,       position: Vector2(G*64, G*33)));")
L("    add(FurnitureComponent(type: FurnitureType.logBench,   position: Vector2(G*57, G*39)));")
L("    add(FurnitureComponent(type: FurnitureType.streetLantern, position: Vector2(G*51, G*37)));")
L("    add(FurnitureComponent(type: FurnitureType.streetLantern, position: Vector2(G*67, G*37)));")
L("    add(FurnitureComponent(type: FurnitureType.woodenSign, position: Vector2(G*62, G*39)));")
L("    add(FurnitureComponent(type: FurnitureType.boulder,    position: Vector2(G*5,  G*38)));")
L("    add(FurnitureComponent(type: FurnitureType.boulder,    position: Vector2(G*13, G*40)));")
L("    add(FurnitureComponent(type: FurnitureType.boulder,    position: Vector2(G*30, G*38)));")
L("    add(FurnitureComponent(type: FurnitureType.boulder,    position: Vector2(G*8,  G*52)));")
L("    add(FurnitureComponent(type: FurnitureType.pineTree,   position: Vector2(G*4,  G*43)));")
L("    add(FurnitureComponent(type: FurnitureType.pineTree,   position: Vector2(G*31, G*49)));")
L("    add(FurnitureComponent(type: FurnitureType.woodenSign, position: Vector2(G*22, G*38)));")
L("    add(FurnitureComponent(type: FurnitureType.boulder,    position: Vector2(G*83, G*11)));")
L("    add(FurnitureComponent(type: FurnitureType.boulder,    position: Vector2(G*83, G*45)));")
L("    add(FurnitureComponent(type: FurnitureType.woodenSign, position: Vector2(G*80, G*27)));")
L("    add(FurnitureComponent(type: FurnitureType.streetLantern, position: Vector2(G*80, G*30)));")
L("    add(FurnitureComponent(type: FurnitureType.logBench,   position: Vector2(G*80, G*23)));")
L("  }")
L("")
L("  // ----------------------------------------------------------------")
L("  // RENDER: scale 2x so each internal pixel = 2x2 screen pixels")
L("  // ----------------------------------------------------------------")
L("  @override")
L("  void render(Canvas canvas) {")
L("    canvas.save();")
L("    canvas.scale(2.0, 2.0); // <-- THE KEY: makes pixels visible")
L("    _drawGrass(canvas);")
L("    _drawForestZone(canvas);")
L("    _drawWater(canvas);")
L("    _drawRiver(canvas);")
L("    _drawBridge(canvas);")
L("    _drawPaths(canvas);")
L("    _drawPlaza(canvas);")
L("    _drawBuilding1(canvas);")
L("    _drawBuilding2(canvas);")
L("    _drawCliffs(canvas);")
L("    _drawLabels(canvas);")
L("    canvas.restore();")
L("  }")
L("")
L("  // ── 1. GRASS TILES ──────────────────────────────────────────────")
L("  // GBA Pokemon: 2 alternating green tiles in 8x8 grid (checker)")
L("  // Tile A: #588040  Tile B: #487038  border seam: #305820")
L("  void _drawGrass(Canvas canvas) {")
L("    const int gw = IW; // 840")
L("    const int gh = IH; // 540")
L("    for (int ty = 0; ty < gh; ty += T) {")
L("      for (int tx = 0; tx < gw; tx += T) {")
L("        final int col = tx ~/ T;")
L("        final int row = ty ~/ T;")
L("        // Classic Pokemon checker pattern")
L("        final bool bright = (col + row) % 2 == 0;")
L("        _r(canvas, tx, ty, T, T, bright ? const Color(0xFF588040) : const Color(0xFF487038));")
L("        // 1-pixel dark seam on right+bottom of every tile — classic GBA look")
L("        _r(canvas, tx+T-1, ty, 1, T, const Color(0xFF305820));")
L("        _r(canvas, tx, ty+T-1, T, 1, const Color(0xFF305820));")
L("        // Sparse grass blades (deterministic, no random)")
L("        final int h = (col * 13 + row * 7) % 16;")
L("        if (h == 0) {")
L("          _r(canvas, tx+2, ty+2, 1, 3, const Color(0xFF80C050));")
L("          _r(canvas, tx+5, ty+1, 1, 4, const Color(0xFF80C050));")
L("        } else if (h == 3) {")
L("          _r(canvas, tx+3, ty+3, 1, 2, const Color(0xFF80C050));")
L("          _r(canvas, tx+6, ty+2, 1, 3, const Color(0xFF80C050));")
L("        }")
L("      }")
L("    }")
L("  }")
L("")
L("  // ── 2. FOREST ZONE ──────────────────────────────────────────────")
L("  // Whispering Woods: darker green tiles + chunky pixel tree canopies")
L("  void _drawForestZone(Canvas canvas) {")
L("    const int fx = T * 38; // starts at tile 38 (world x=608)")
L("    const int fw = T * 40; // 40 tiles wide")
L("    const int fh = T * 26; // top half only")
L("    // Dark grass base")
L("    for (int ty = 0; ty < fh; ty += T) {")
L("      for (int tx = fx; tx < fx+fw; tx += T) {")
L("        final int col = tx ~/ T;")
L("        final int row = ty ~/ T;")
L("        final bool bright = (col + row) % 2 == 0;")
L("        _r(canvas, tx, ty, T, T, bright ? const Color(0xFF305828) : const Color(0xFF284820));")
L("        _r(canvas, tx+T-1, ty, 1, T, const Color(0xFF182810));")
L("        _r(canvas, tx, ty+T-1, T, 1, const Color(0xFF182810));")
L("      }")
L("    }")
L("    // Border tree row — chunky GBA-style 2-layer canopy")
L("    for (int tx = 0; tx < IW; tx += T*3) {")
L("      _pixelTree(canvas, tx, 0);")
L("    }")
L("    for (int ty = T*3; ty < IH - T*3; ty += T*3) {")
L("      _pixelTree(canvas, 0, ty);")
L("    }")
L("    for (int tx = 0; tx < IW; tx += T*3) {")
L("      _pixelTree(canvas, tx, IH - T*4);")
L("    }")
L("    // Interior forest trees")
L("    for (int tx = fx + T; tx < fx+fw; tx += T*5) {")
L("      for (int ty = T*2; ty < fh; ty += T*5) {")
L("        _pixelTree(canvas, tx, ty);")
L("      }")
L("    }")
L("  }")
L("")
L("  // GBA-style pixel tree: flat top canopy in 2 shades + trunk")
L("  void _pixelTree(Canvas canvas, int tx, int ty) {")
L("    // Shadow outline")
L("    _r(canvas, tx,    ty+2,  T*3,   T*2+2, const Color(0xFF182810));")
L("    _r(canvas, tx+2,  ty,    T*3-4, T*4,   const Color(0xFF182810));")
L("    // Dark canopy fill")
L("    _r(canvas, tx+1,  ty+2,  T*3-2, T*2,   const Color(0xFF284820));")
L("    _r(canvas, tx+3,  ty+1,  T*3-6, T*3+2, const Color(0xFF284820));")
L("    // Mid canopy")
L("    _r(canvas, tx+2,  ty+3,  T*3-4, T*2,   const Color(0xFF388030));")
L("    _r(canvas, tx+4,  ty+1,  T*3-8, T*3,   const Color(0xFF388030));")
L("    // Highlight pixel clusters (top-left lit)")
L("    _r(canvas, tx+4,  ty+1,  4,     3,     const Color(0xFF58A840));")
L("    _r(canvas, tx+2,  ty+3,  3,     2,     const Color(0xFF58A840));")
L("    // Trunk")
L("    _r(canvas, tx+T, ty+T*3, 4, T,         const Color(0xFF604020));")
L("    _r(canvas, tx+T+4, ty+T*3, 4, T,       const Color(0xFF402810));")
L("  }")
L("")
L("  // ── 3. WATER / OCEAN ────────────────────────────────────────────")
L("  // Beach sand then 4 columns of ocean, deepening in colour")
L("  void _drawWater(Canvas canvas) {")
L("    const int beachX = 640; // world 1280 / 2")
L("    const int waveX  = 696; // world 1392 / 2")
L("    // Sand (tiled)")
L("    for (int ty = 0; ty < IH; ty += T) {")
L("      for (int tx = beachX; tx < waveX; tx += T) {")
L("        final bool bright = ((tx ~/ T) + (ty ~/ T)) % 2 == 0;")
L("        _r(canvas, tx, ty, T, T, bright ? const Color(0xFFF0C870) : const Color(0xFFD8A848));")
L("      }")
L("    }")
L("    // Wet sand line")
L("    _r(canvas, waveX - 4, 0, 4, IH, const Color(0xFFC09030));")
L("    // Ocean bands — 4 GBA blue shades")
L("    const List<Color> oc = [")
L("      Color(0xFF38B8F0), // shallow")
L("      Color(0xFF2888D0), // mid")
L("      Color(0xFF1858A8), // deep")
L("      Color(0xFF102878), // abyss")
L("    ];")
L("    const int bandW = (IW - waveX) ~/ 4;")
L("    for (int i = 0; i < 4; i++) {")
L("      _r(canvas, waveX + i*bandW, 0, bandW, IH, oc[i]);")
L("    }")
L("    // Wave lines — 2px horizontal strips, staggered each row")
L("    for (int ty = 0; ty < IH; ty += T*3) {")
L("      final int stagger = (ty ~/ (T*3)) % 2 == 0 ? 4 : 0;")
L("      for (int tx = waveX + stagger; tx < IW - 4; tx += T*3) {")
L("        _r(canvas, tx, ty,   12, 1, const Color(0xFF88D8F8)); // bright")
L("        _r(canvas, tx, ty+1,  8, 1, const Color(0xFFF8FCFF)); // white")
L("      }")
L("    }")
L("    // Foam pixels at shore edge")
L("    for (int ty = 0; ty < IH; ty += T) {")
L("      final bool odd = (ty ~/ T) % 2 == 0;")
L("      _r(canvas, waveX, ty + (odd ? 0 : 4), 3, 4, const Color(0xFFF8FCFF));")
L("    }")
L("    // Pier")
L("    const int px2 = 648; const int py2 = 232;")
L("    const int pw2 = 144; const int ph2 = 32;")
L("    for (int tx = px2; tx < px2+pw2; tx += 7) {")
L("      _r(canvas, tx, py2, 6, ph2, const Color(0xFFA06820)); // plank")
L("      _r(canvas, tx, py2, 6, 2,   const Color(0xFFD09040)); // highlight")
L("    }")
L("    _r(canvas, px2, py2,    pw2, 3, const Color(0xFF603010)); // top rail")
L("    _r(canvas, px2, py2+ph2-3, pw2, 3, const Color(0xFF603010)); // bot rail")
L("    for (int tx = px2; tx <= px2+pw2; tx += 32) {")
L("      _r(canvas, tx-1, py2+ph2, 4, 14, const Color(0xFF402010)); // piling")
L("    }")
L("  }")
L("")
L("  // ── 4. RIVER ────────────────────────────────────────────────────")
L("  // Straight vertical water strip — axis-aligned, GBA blue palette")
L("  void _drawRiver(Canvas canvas) {")
L("    const int rL = T * 46; // world x=736 / 2 = 368")
L("    const int rW = T * 4;  // 4 tiles wide (world = 8 tiles)")
L("    const int rY = T * 26; // starts at world y=832 / 2... wait, world G*26 = 416, /2 = 208")
L("    // Actually: world coords / 2 = internal coords")
L("    // rL_world = G*46 = 736, internal = 368")
L("    // But T=8, T*46 = 368. Correct.")
L("    const int rLi = T * 46; // == 368")
L("    const int rYi = T * 26; // == 208")
L("    const int rWi = T * 4;")
L("    // Mud banks")
L("    _r(canvas, rLi-2, rYi, rWi+4, IH-rYi, const Color(0xFF906040));")
L("    // Water main")
L("    _r(canvas, rLi, rYi, rWi, IH-rYi, const Color(0xFF2870C8));")
L("    // Centre deep channel")
L("    _r(canvas, rLi+rWi~/3, rYi, rWi~/3, IH-rYi, const Color(0xFF1850A0));")
L("    // Ripple lines every 3 tiles")
L("    for (int ty = rYi + T; ty < IH; ty += T*3) {")
L("      _r(canvas, rLi+2,    ty, 6, 1, const Color(0xFF88C8F0));")
L("      _r(canvas, rLi+rWi-8, ty+T, 6, 1, const Color(0xFF88C8F0));")
L("    }")
L("    // Shore foam dots")
L("    for (int ty = rYi; ty < IH; ty += T) {")
L("      final bool odd = (ty ~/ T) % 2 == 0;")
L("      _r(canvas, rLi, ty + (odd ? 0 : 3), 2, 3, const Color(0xFFF0F8FF));")
L("      _r(canvas, rLi+rWi-2, ty + (odd ? 3 : 0), 2, 3, const Color(0xFFF0F8FF));")
L("    }")
L("    // Lily pads")
L("    void lily(int lx, int ly) {")
L("      _r(canvas, lx, ly, T, T, const Color(0xFF207820));")
L("      _r(canvas, lx+2, ly+2, 4, 4, const Color(0xFF106010));")
L("      _r(canvas, lx+3, ly+1, 2, 2, const Color(0xFFE82848)); // flower")
L("    }")
L("    lily(rLi+4,  T*29);")
L("    lily(rLi+10, T*35);")
L("    lily(rLi+2,  T*50);")
L("  }")
L("")
L("  // ── 5. BRIDGE ───────────────────────────────────────────────────")
L("  void _drawBridge(Canvas canvas) {")
L("    const int bx = T*45; const int by = T*42;")
L("    const int bw = T*6;  const int bh = T*4;")
L("    // Shadow")
L("    _r(canvas, bx+2, by+bh, bw, 6, const Color(0x40000000));")
L("    // Planks — alternating 2-tone")
L("    for (int tx = bx; tx < bx+bw; tx += 7) {")
L("      _r(canvas, tx, by, 5, bh, const Color(0xFFA87030));")
L("      _r(canvas, tx+1, by, 3, 2, const Color(0xFFD09848)); // highlight")
L("    }")
L("    // Top/bottom rails")
L("    _r(canvas, bx-2, by,     bw+4, 4, const Color(0xFF704820));")
L("    _r(canvas, bx-2, by+bh-4, bw+4, 4, const Color(0xFF704820));")
L("    // Rope posts")
L("    for (int tx = bx; tx <= bx+bw; tx += bw~/2) {")
L("      _r(canvas, tx-1, by-4, 4, bh+8, const Color(0xFF503010));")
L("    }")
L("  }")
L("")
L("  // ── 6. DIRT PATHS ───────────────────────────────────────────────")
L("  // Strict H or V axis-aligned only. GBA: tan/cream 3-shade bevel.")
L("  void _drawPaths(Canvas canvas) {")
L("    void path(int x, int y, int w, int h) {")
L("      // Base fill")
L("      _r(canvas, x, y, w, h, const Color(0xFFD8B878));")
L("      // Top/left highlight")
L("      _r(canvas, x, y, w, 2, const Color(0xFFF0D098));")
L("      _r(canvas, x, y, 2, h, const Color(0xFFF0D098));")
L("      // Bottom/right shadow")
L("      _r(canvas, x+w-2, y, 2, h, const Color(0xFFB09050));")
L("      _r(canvas, x, y+h-2, w, 2, const Color(0xFFB09050));")
L("      // Centre track line (horizontal paths: 2 h-lines; vertical: 2 v-lines)")
L("      if (w > h) {")
L("        _r(canvas, x+4, y + h~/3,     w-8, 1, const Color(0xFFB09050));")
L("        _r(canvas, x+4, y + 2*h~/3,   w-8, 1, const Color(0xFFB09050));")
L("      } else {")
L("        _r(canvas, x + w~/3,   y+4, 1, h-8, const Color(0xFFB09050));")
L("        _r(canvas, x + 2*w~/3, y+4, 1, h-8, const Color(0xFFB09050));")
L("      }")
L("    }")
L("    // Village-to-Route1 H connector")
L("    path(T*34, T*16, T*11, T*3);")
L("    // Route 1 main horizontal road")
L("    path(T*45, T*16, T*31, T*3);")
L("    // Route 1 south-turn vertical")
L("    path(T*75, T*16, T*3, T*14);")
L("    // Pier connector H")
L("    path(T*75, T*29, T*6, T*3);")
L("    // South to camp vertical")
L("    path(T*54, T*19, T*3, T*13);")
L("    // Bridge approaches H")
L("    path(T*39, T*42, T*6, T*4);")
L("    path(T*51, T*42, T*8, T*4);")
L("    // Mountain trails V")
L("    path(T*17, T*27, T*2, T*7);")
L("    path(T*21, T*40, T*2, T*8);")
L("  }")
L("")
L("  // ── 7. COBBLESTONE PLAZA ────────────────────────────────────────")
L("  // GBA style: grey bricks with 1px dark mortar lines, staggered")
L("  void _drawPlaza(Canvas canvas) {")
L("    const int px = T*7; const int py = T*12;")
L("    const int pw = T*28; const int ph = T*15;")
L("    // Base stone colour")
L("    _r(canvas, px, py, pw, ph, const Color(0xFFC0C0B0));")
L("    // Brick pattern: staggered horizontal rows, T=8 brick height, T*2=16 brick width")
L("    const int bh = T;  // brick height = 8 px")
L("    const int bw = T*2; // brick width = 16 px")
L("    for (int ty = py; ty < py+ph; ty += bh) {")
L("      final int row = (ty - py) ~/ bh;")
L("      final int offset = (row % 2) * bw~/2;")
L("      // Horizontal mortar line")
L("      _r(canvas, px, ty, pw, 1, const Color(0xFF808070));")
L("      // Vertical mortar between bricks in this row")
L("      for (int tx = px + offset; tx < px+pw; tx += bw) {")
L("        _r(canvas, tx, ty, 1, bh, const Color(0xFF808070));")
L("        // Brick highlight top-left pixel")
L("        _r(canvas, tx+1, ty+1, bw-3, 1, const Color(0xFFD8D8C8));")
L("        _r(canvas, tx+1, ty+2, 1, bh-3,const Color(0xFFD8D8C8));")
L("      }")
L("    }")
L("    // Border")
L("    _r(canvas, px, py, pw, 2, const Color(0xFF707060));")
L("    _r(canvas, px, py+ph-2, pw, 2, const Color(0xFF707060));")
L("    _r(canvas, px, py, 2, ph, const Color(0xFF707060));")
L("    _r(canvas, px+pw-2, py, 2, ph, const Color(0xFF707060));")
L("  }")
L("")
L("  // ── 8. BUILDINGS ────────────────────────────────────────────────")
L("  // GBA Pokemon house: flat pixel-art, 3-shade roof, cream wall, brown trim")
L("  void _drawBuilding1(Canvas canvas) {")
L("    // Red-roof cottage (world G*5,G*5, w=G*12, h=G*8)")
L("    const int bx = T*5; const int by = T*5;")
L("    const int bw = T*12; const int bh = T*8; const int rh = T*4;")
L("    _building(canvas, bx, by, bw, bh, rh,")
L("      const Color(0xFFC02020), // roof dark")
L("      const Color(0xFFE03030), // roof mid")
L("      const Color(0xFFF05050), // roof light")
L("    );")
L("    // Chimney")
L("    _r(canvas, bx+bw-20, by-8, 8, 20, const Color(0xFF803020));")
L("    _r(canvas, bx+bw-22, by-10, 12, 3, const Color(0xFF606060));")
L("    // Door")
L("    _door(canvas, bx + bw~/2 - 6, by+rh+12);")
L("    // Windows")
L("    _window(canvas, bx+8, by+rh+10);")
L("    _window(canvas, bx+bw-20, by+rh+10);")
L("  }")
L("")
L("  void _drawBuilding2(Canvas canvas) {")
L("    // Blue-roof larger house (world G*20,G*4, w=G*14, h=G*9)")
L("    const int bx = T*20; const int by = T*4;")
L("    const int bw = T*14; const int bh = T*9; const int rh = T*4;")
L("    _building(canvas, bx, by, bw, bh, rh,")
L("      const Color(0xFF102888), // roof dark")
L("      const Color(0xFF2040B0), // roof mid")
L("      const Color(0xFF4060D8), // roof light")
L("    );")
L("    // Double door")
L("    _r(canvas, bx+bw~/2-10, by+rh+12, 20, 22, const Color(0xFF603010));")
L("    _r(canvas, bx+bw~/2-1,  by+rh+12, 2, 22, const Color(0xFF301808)); // divider")
L("    _r(canvas, bx+bw~/2-9,  by+rh+14, 6, 8, const Color(0xFF88C8E8)); // glass l")
L("    _r(canvas, bx+bw~/2+3,  by+rh+14, 6, 8, const Color(0xFF88C8E8)); // glass r")
L("    _window(canvas, bx+8,    by+rh+10);")
L("    _window(canvas, bx+bw-20, by+rh+10);")
L("  }")
L("")
L("  // Shared building draw: wall + triangle roof in 3 shades")
L("  void _building(Canvas canvas, int bx, int by, int bw, int bh, int rh,")
L("      Color rDark, Color rMid, Color rLight) {")
L("    // Drop shadow")
L("    _r(canvas, bx+4, by+bh-4, bw+4, 8, const Color(0x40000000));")
L("    // Wall")
L("    _r(canvas, bx, by+rh, bw, bh-rh, const Color(0xFFF0E8D8));")
L("    // Wall timber frame")
L("    _r(canvas, bx,      by+rh, 4, bh-rh, const Color(0xFF603010));")
L("    _r(canvas, bx+bw-4, by+rh, 4, bh-rh, const Color(0xFF603010));")
L("    _r(canvas, bx,      by+rh, bw, 4,    const Color(0xFF603010));")
L("    // Foundation")
L("    _r(canvas, bx, by+bh-4, bw, 4, const Color(0xFF707080));")
L("    // Roof — GBA pixel triangle built from horizontal lines")
L("    final int halfW = bw ~/ 2;")
L("    for (int i = 0; i < rh; i++) {")
L("      final int lineW = (bw * (rh - i)) ~/ rh;")
L("      final int lx = bx + (bw - lineW) ~/ 2;")
L("      // 3-shade: dark at bottom, mid fill, light at top 2px")
L("      final Color c = (i < 2) ? rLight : (i < rh - 2 ? rMid : rDark);")
L("      _r(canvas, lx, by + i, lineW, 1, c);")
L("    }")
L("    // Roof outline (dark trim lines)")
L("    for (int i = 0; i < rh; i++) {")
L("      final int lineW = (bw * (rh - i)) ~/ rh;")
L("      final int lx = bx + (bw - lineW) ~/ 2;")
L("      _r(canvas, lx, by+i, 2, 1, const Color(0xFF401808)); // left edge")
L("      _r(canvas, lx+lineW-2, by+i, 2, 1, const Color(0xFF401808)); // right edge")
L("    }")
L("    // Eave (bottom of roof)")
L("    _r(canvas, bx-2, by+rh-4, bw+4, 4, rDark);")
L("    _r(canvas, bx-2, by+rh-4, bw+4, 2, rMid);")
L("  }")
L("")
L("  void _window(Canvas canvas, int wx, int wy) {")
L("    _r(canvas, wx,    wy,    12, 10, const Color(0xFF401808)); // frame")
L("    _r(canvas, wx+1,  wy+1,  10,  8, const Color(0xFFF8E878)); // glow")
L("    _r(canvas, wx+6,  wy+1,  1,   8, const Color(0xFF401808)); // cross h")
L("    _r(canvas, wx+1,  wy+5,  10,  1, const Color(0xFF401808)); // cross v")
L("    _r(canvas, wx+1,  wy+1,  4,   3, const Color(0xFFFFFCB0)); // top-left bright")
L("    // Shutters")
L("    _r(canvas, wx-4, wy, 3, 10, const Color(0xFF1E3A8A));")
L("    _r(canvas, wx+12, wy, 3, 10, const Color(0xFF1E3A8A));")
L("    // Flower box")
L("    _r(canvas, wx-2, wy+10, 16, 3, const Color(0xFF603010));")
L("    _r(canvas, wx,   wy+11, 2, 2, const Color(0xFFE82848));")
L("    _r(canvas, wx+4, wy+10, 2, 3, const Color(0xFFF8C820));")
L("    _r(canvas, wx+8, wy+11, 2, 2, const Color(0xFFE840A0));")
L("  }")
L("")
L("  void _door(Canvas canvas, int dx, int dy) {")
L("    _r(canvas, dx,    dy,    14, 20, const Color(0xFF603010)); // frame")
L("    _r(canvas, dx+2,  dy+2,  10, 10, const Color(0xFF804020)); // panel top")
L("    _r(canvas, dx+2,  dy+13, 10,  5, const Color(0xFF804020)); // panel bot")
L("    _r(canvas, dx+10, dy+10, 2,  2, const Color(0xFFF8D820)); // knob")
L("  }")
L("")
L("  // ── 9. CLIFF LEDGES ─────────────────────────────────────────────")
L("  // GBA cliff: 3 horizontal bands: highlight / mid / shadow")
L("  void _drawCliffs(Canvas canvas) {")
L("    _cliffLedge(canvas, T*2, T*34, T*36);")
L("    _cliffLedge(canvas, T*2, T*48, T*36);")
L("    // Cave entrance")
L("    const int cx = T*11; const int cy = T*35;")
L("    _r(canvas, cx,    cy,    16, 3,  const Color(0xFF181008)); // top))")
L("    _r(canvas, cx-2,  cy+3,  4,  16, const Color(0xFF181008)); // left wall")
L("    _r(canvas, cx+14, cy+3,  4,  16, const Color(0xFF181008)); // right wall")
L("    _r(canvas, cx,    cy+3,  16, 16, const Color(0xFF080604)); // interior")
L("    _r(canvas, cx-4,  cy+2,  24, 3,  const Color(0xFF585858)); // ledge above")
L("  }")
L("")
L("  void _cliffLedge(Canvas canvas, int x, int y, int w) {")
L("    const int h = T*2;")
L("    // Rock face fill")
L("    _r(canvas, x, y, w, h, const Color(0xFF906040));")
L("    // Top highlight strip")
L("    _r(canvas, x, y, w, 2, const Color(0xFFC08050));")
L("    _r(canvas, x, y+2, w, 2, const Color(0xFFA87040));")
L("    // Middle strata line")
L("    _r(canvas, x, y+h~/2, w, 2, const Color(0xFF784830));")
L("    // Bottom shadow strip")
L("    _r(canvas, x, y+h-3, w, 3, const Color(0xFF603020));")
L("    // Vertical crack pixels")
L("    int ci = x + 12;")
L("    while (ci < x + w) {")
L("      _r(canvas, ci, y+3, 1, h-5, const Color(0xFF603020));")
L("      ci += 24;")
L("    }")
L("  }")
L("")
L("  // ── 10. LABELS ──────────────────────────────────────────────────")
L("  // GBA-style region signs: solid colour box, bold pixel text")
L("  void _drawLabels(Canvas canvas) {")
L("    _label(canvas, 'VERDANT VILLAGE',    T*8,  T*3,  const Color(0xFF206010));")
L("    _label(canvas, 'WHISPERING WOODS',   T*46, T*3,  const Color(0xFF184808));")
L("    _label(canvas, 'CRYSTAL BAY',        T*82, T*3,  const Color(0xFF104870));")
L("    _label(canvas, 'CRAGGY RIDGE',       T*5,  T*32, const Color(0xFF703010));")
L("    _label(canvas, 'ADVENTURE CAMP',     T*52, T*30, const Color(0xFF806010));")
L("    _label(canvas, 'RIVER CROSSING',     T*52, T*47, const Color(0xFF106040));")
L("  }")
L("")
L("  void _label(Canvas canvas, String text, int x, int y, Color bgColor) {")
L("    final tp = TextPainter(")
L("      text: TextSpan(text: text, style: const TextStyle(")
L("        color: Color(0xFFFFFFFF),")
L("        fontSize: 5,  // small! rendered at 2x = 10px on screen")
L("        fontWeight: FontWeight.w900,")
L("        letterSpacing: 0.5,")
L("        height: 1.2,")
L("      )),")
L("      textDirection: TextDirection.ltr,")
L("    )..layout();")
L("    final int bw = tp.width.ceil() + 8;")
L("    final int bh = tp.height.ceil() + 6;")
L("    // Background box with 1px dark border")
L("    _r(canvas, x-1, y-1, bw+2, bh+2, const Color(0xFF000000));")
L("    _r(canvas, x,   y,   bw,   bh,   bgColor);")
L("    _r(canvas, x,   y,   bw,   1,    const Color(0x60FFFFFF)); // top sheen")
L("    tp.paint(canvas, Offset((x + 4).toDouble(), (y + 3).toDouble()));")
L("  }")
L("")
L("  // ── ZONE NAME HELPER ────────────────────────────────────────────")
L("  static String getZoneName(Vector2 pos) {")
L("    if (pos.x >= 1280) return 'Crystal Bay';")
L("    if (pos.y < 512) return pos.x < 608 ? 'Verdant Village' : 'Whispering Woods';")
L("    if (pos.x < 592) return 'Craggy Ridge';")
L("    if (pos.y < 752) return 'Adventure Camp';")
L("    return 'River Crossing';")
L("  }")
L("}")

out = r'lib\features\world\game\components\tile_map.dart'
with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('Written', len(lines), 'lines')
